//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blackjack.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpellenEntities2 : DbContext
    {
        public SpellenEntities2()
            : base("name=SpellenEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SessieEntity> SessieEntities { get; set; }
        public virtual DbSet<speler> spelers { get; set; }
        public virtual DbSet<spellen> spellens { get; set; }
        public virtual DbSet<uitslagen> uitslagens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
